### ISSUE TITLE
[FE]Feat 옷장 디자인 수정 디테일 디자인 정상화

### ISSUE THREAD

**Issue by chundang** [UMC-FITple/Frontend#106]
## 💻 Feature 설명
> 옷장 디자인 디테일 디자인 정상화
<br>

## 📝 To-do
**메인주제**
- [ ] 할 일
- [x] 끝난 일
- [x] 옷장 디자인 수영님거 살리기 
- [x] 디테일 디자인 정상화
- [x]  네비게이트  to detail id로
<br>
