### ISSUE TITLE
[FE][FEAT] 등록 페이지 디자인 수정 / 이미지 업로드 구현

### ISSUE THREAD

**Issue by kangsuyeong** [UMC-FITple/Frontend#137]
## 💻 Feature 설명
> 등록 페이지 디자인 수정 / 이미지 업로드 구현

<br>

## 📝 To-do
**메인주제**
- [x] 등록 페이지 디자인 수정
- [x] 등록 팝업 디자인 수정
- [x] 이미지 업로드 구현
- [x] 업로드 후 옷장 페이지로 이동
<br>

## 📸 스크린샷
**등록팝업 디자인 수정**
![image](https://github.com/user-attachments/assets/df8b5453-ffe5-46ec-bfe5-d428e04be951)

https://github.com/user-attachments/assets/4065f269-bfc5-4668-86c0-2536dd8fb3fe

<br>

## 📚 참고문헌 / 기타
-
