### ISSUE TITLE
[FE][REFACTOR] Component, Pages 폴더 구조 변경

### ISSUE THREAD

**Issue by SeyeonJang** [UMC-FITple/Frontend#19]
## ✅ Refactoring 설명
> components, pages 폴더가 두 개씩 있고 component / components 폴더가 나뉘어져 있는 것을 하나로 통일
<br>

## 📝 To-do
**폴더 리팩토링**
- [x] pages 하나로 합치기
- [x] components 하나로 합치기
- [x] component 폴더 삭제
- [x] Navbar Component 두 개 중 하나 삭제
<br>

## 📸 스크린샷
- 기존 폴더 구조(왼), 변경 폴더 구조(오)
<img width="243" alt="image" src="https://github.com/user-attachments/assets/9b60191f-5167-4374-8f55-2c4c9dce5de3">
<img width="246" alt="image" src="https://github.com/user-attachments/assets/a3009594-8c2e-4236-8c58-dd1f89e50245">
