### ISSUE TITLE
[FE][FEAT] Navbar 검색 페이지 blue 디자인 / 검색 페이지 구현

### ISSUE THREAD

**Issue by kangsuyeong** [UMC-FITple/Frontend#33]
## 💻 Feature 설명
> Navbar 검색 페이지 blue ver 디자인 , 검색 페이지 구현
<br>

## 📝 To-do
**메인주제**
- [x] Navbar 검색 페이지 blue 디자인 구현
- [x] Navbar 블루 레이아웃 생성
- [x] SearchBox 컴포넌트 구현/분리
- [x] Navbar에 검색페이지 연결
- [x] 검색 - 메인화면
- [ ] 검색 - 결과없음
- [ ] 검색 - 통합검색 
- [x] 검색 - 브랜드
- [x] 검색 - 브랜드 - 등록x
<br>

## 📸 스크린샷
**Navbar 검색 페이지 blue 디자인 구현**
![image](https://github.com/user-attachments/assets/aadb1c4d-0ef8-4a06-8708-65389890ebd1)

**Navbar 블루 레이아웃 생성**
![image](https://github.com/user-attachments/assets/e5cff4b5-3f7c-488d-ab51-1e5e3f584c8d)

**SearchBox 컴포넌트 구현/분리**
![image](https://github.com/user-attachments/assets/f3cd5e18-a048-44c2-a867-26a73d52d6e9)
![image](https://github.com/user-attachments/assets/aed523a3-70ab-453c-a9ba-84a30667922f)

**검색 - 메인화면**
![image](https://github.com/user-attachments/assets/677e8181-da6a-410d-89ea-af2f911b3b74)

**검색 - 브랜드**
![image](https://github.com/user-attachments/assets/40fb9f77-abe6-4bec-bf4b-6b0220436f60)

**검색 - 브랜드 - 등록x**
![image](https://github.com/user-attachments/assets/c1e7544b-d9d9-48b8-8e75-4febce222893)

<br>

## 📚 참고문헌 / 기타
-
