### ISSUE TITLE
[FE][FEAT] 추천 - STORE 및 API 연결 준비

### ISSUE THREAD

**Issue by junhyuk0305** [UMC-FITple/Frontend#46]
## 💻 Feature 설명
> 추천 API 연결 준비 및 STORE
<br>

## 📝 To-do
**메인주제**
- [ ] 예시 데이터 만들기
- [ ] 메인 예시 유저 FETCH
- [ ] 모두보기 예시유저 FETCH
- [ ] 유저카드 FOLLOW 여부
- [ ] 유저 프로필 FETCH
- [ ] 유저 프로필 FOLLOW 여부
- [ ] 옷장 NAV 분류
- [ ] 옷장 즐찾 여부
- [ ] 상품 FETCH
- [ ] FIXED 구현 및 FETCH

<br>

## 📚 참고문헌 / 기타
-
