### ISSUE TITLE
[FE][FEAT] 프로필 페이지 UI 구현

### ISSUE THREAD

**Issue by kangsuyeong** [UMC-FITple/Frontend#62]
## 💻 Feature 설명
> 프로필 페이지 UI 구현
<br>

## 📝 To-do
**메인주제**
- [x] 프로필 페이지 - 좋아하는 옷
- [x] 프로필 페이지 -  관심있는 옷
- [x] 프로필 페이지 - 내 체형정보
<br>

## 📸 스크린샷
**프로필 페이지 - 좋아하는 옷**
![image](https://github.com/user-attachments/assets/c53c6086-7d55-4304-8085-e4a48ca20e39)

**프로필 페이지 - 관심있는 옷**
![image](https://github.com/user-attachments/assets/39f709e2-d4be-4da5-8666-7fca41eac134)

**프로필 페이지 - 내 체형정보**
![image](https://github.com/user-attachments/assets/9e5397d3-27c2-4929-ae2b-16e8f002e227)

<br>

## 📚 참고문헌 / 기타
-
