### ISSUE TITLE
[FE][FEAT] 로그인, 회원가입 API 연결

### ISSUE THREAD

**Issue by SeyeonJang** [UMC-FITple/Frontend#65]
## 💻 Feature 설명
> 로그인, 회원가입 페이지 전체 API 연결
<br>

## 📝 To-do
**로그인**
- [x] 로그인 토큰 관리

**회원가입**
- [x] 회원가입 API 연결 - 회원가입 api

**같이 하면 좋은 것**
- [ ] 회원정보 작성 API 연결 - 내 프로필 설정 api
- [ ] ID 찾기 API 연결 - 아이디 찾기 api
- [ ] PW 찾기 API 연결 - 비밀번호 변경 권한 확인, 비밀번호 변경 api
<br>

## 📸 스크린샷
- zustand로 토큰 관리
![image](https://github.com/user-attachments/assets/bbf1ece3-1a70-41aa-b5fd-c761041e52d3)

<br>
